# Generated by Django 5.0.7 on 2024-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recipes', models.JSONField()),
                ('rating', models.FloatField()),
                ('numReviews', models.IntegerField()),
                ('cookList', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
